name: Add an Article to Replication
description: Add an article to replication
title: "[Repl]: "
labels: ["database","replication"]
body:
  - type: markdown
    attributes:
      value: |
        Let's add an article to replication on sql1.
  - type: input
    id: database
    attributes:
      label: Database to replicate from
      description: Publisher database that contains the article
    validations:
      required: true
  - type: input
    id: schema
    attributes:
      label: Article Schema
      description: Schema of the article
    validations:
      required: true
  - type: input
    id: article
    attributes:
      label: Article Name
      description: Name of the article
    validations:
      required: true
