name: Terraform

on:
  push:
    branches:
      - main

env:
  working-directory: dbatoolsAPI\infra\

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      # Validate terraform files
      - name: Terraform Validate
        run: terraform validate

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check -recursive
      
      # Perform a security scan of the terraform code using checkov
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with: 
          framework: terraform
          skip_check: CKV_AZURE_224,CKV_AZURE_229,CKV_AZURE_190,CKV_AZURE_33,CKV_AZURE_206,CKV_AZURE_212,CKV_AZURE_225,CKV2_AZURE_1,CKV2_AZURE_45,CKV2_AZURE_33,CKV_AZURE_23,CKV2_AZURE_27,CKV_AZURE_24,CKV_AZURE_41

      - name: Terraform Apply
        env:
          TF_VAR_administrator_login_password: ${{ secrets.SQL_ADMIN_PWD }}
        run: terraform apply -auto-approve
