on:
  issues:
    types: [opened,reopened]

name: Run Command
jobs:
  add_article:
    runs-on: self-hosted
    if: contains(github.event.issue.labels.*.name, 'test')
    steps:
    - name: Where am i
      shell: pwsh
      run: |
        pwd
        ls
    - name: Close Issue
      run: |
        cd C:\GitHub\PASS-BTB
        pwd
        gh issue close ${{ github.event.issue.number }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

# TODO: closing the issue doesn't work?!?