on:
  issues:
    types: [opened,reopened]

name: Run Command
jobs:
  add_article:
    runs-on: self-hosted
    if: contains(github.event.issue.labels.*.name, 'test')
    permissions:
      issues: write      # Add this to ensure proper permissions
      contents: read     # Add this if you need repo access
    steps:
    # Checkout code
    - uses: actions/checkout@main

    - name: Where am i
      shell: pwsh
      run: |
        pwd
        ls

    - name: Close Issue
      shell: pwsh       # Explicitly specify PowerShell
      run: |
        gh auth login --with-token $env:GITHUB_TOKEN
        gh issue close ${{ github.event.issue.number }} -R JessAndRob/PASS-BTB
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}