on:
  issues:
    types: [opened,reopened]

name: Run Command
jobs:
  add_article:
    runs-on: self-hosted
    if: contains(github.event.issue.labels.*.name, 'test')
    steps:

    # Checkout code
    - uses: actions/checkout@main

    - name: Where am i
      shell: pwsh
      run: |
        pwd
        ls
    - name: Close Issue
      run: |
        gh issue close ${{ github.event.issue.number }} -R JessAndRob/PASS-BTB
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

# TODO: closing the issue doesn't work?!?