on:
  workflow_dispatch:

name: Run Command
jobs:
  run_command:
    runs-on: self-hosted
    steps:
    # Log into Azure
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Where am i
      shell: pwsh
      run: |
        pwd
        ls
    - name: Any dbatools?
      shell: pwsh
      run: |
        Get-Module dbatools -ListAvailable
    - name: Any databases
      shell: pwsh
      run: |
        Get-DbaDatabase -SqlInstance sql1

      

    

