on:
  issues:
    types: [opened]

name: Run Command
jobs:
  run_command:
    runs-on: self-hosted
    #if: contains(github.event.issue.labels.*.name, 'replication')
    steps:
    - name: Where am i
      shell: pwsh
      run: |
        pwd
        ls
    - name: Parse issue
      id: parse
      uses: onmax/issue-form-parser@v1.5
      with:
        issue_number: ${{ github.event.issue.number }}

    # Examples on how to use the output
    - name: Show parsed payload data
      run: |
        # Using the character `'` to prevent all characters enclosed within
        # them from being treated as special characters (e.g. $ or `)
        write-host '${{ steps.parse.outputs.payload }}'

    - name: Any dbatools?
      shell: pwsh
      run: |
        Get-Module dbatools -ListAvailable
    - name: Any databases
      shell: pwsh
      run: |
        Get-DbaDatabase -SqlInstance sql1

      
    

