on:
  issues:
    types: [opened,reopened]

name: Run Command
jobs:
  run_command:
    runs-on: self-hosted
    #if: contains(github.event.issue.labels.*.name, 'replication')
    steps:
    - name: Where am i
      shell: pwsh
      run: |
        pwd
        ls
    - name: Issue Forms Body Parser
      id: parse
      uses: zentered/issue-forms-body-parser@v2.0.0
  
    - name: lets see what we got
      shell: pwsh
      run: |
        $results = '${{ toJSON(steps.parse.outputs.data) }}'
        $results = $results | ConvertFrom-Json | Select-Object -expand article-name

        $results
        $results.text

    - name: Any dbatools?
      shell: pwsh
      run: |
        Get-Module dbatools -ListAvailable
    - name: Any databases
      shell: pwsh
      run: |
        Get-DbaDatabase -SqlInstance sql1

      
    

