on:
  issues:
    types: [opened,reopened]

name: Run Command
jobs:
  run_command:
    runs-on: self-hosted
    #if: contains(github.event.issue.labels.*.name, 'replication')
    steps:
    - name: Where am i
      shell: pwsh
      run: |
        pwd
        ls
    - name: Issue Forms Body Parser
      id: parse
      uses: zentered/issue-forms-body-parser@v2.0.0
  
    - name: lets see what we got
      shell: pwsh
      run: |
        $results = '${{ toJSON(steps.parse.outputs.data) }}'
        $results = $results | ConvertFrom-Json 

        $finalRes = $results | ConvertFrom-Json # not sure why we need 2?

        write-host ('Database: {0}' -f $finalRes.'database'.text)
        write-host ('Schema: {0}' -f $finalRes.'schema'.text)
        write-host ('Article: {0}' -f $finalRes.'article'.text)        

    - name: Any dbatools?
      shell: pwsh
      run: |
        Get-Module dbatools -ListAvailable
    - name: Any databases
      shell: pwsh
      run: |
        Get-DbaDatabase -SqlInstance sql1
    - name: Add the article
      shell: pwsh
      run: |
        $results = '${{ toJSON(steps.parse.outputs.data) }}'
        $results = $results | ConvertFrom-Json 

        $finalRes = $results | ConvertFrom-Json # not sure why we need to do this twice?

        write-host ('Database: {0}' -f $finalRes.'database'.text)
        write-host ('Schema: {0}' -f $finalRes.'schema'.text)
        write-host ('Article: {0}' -f $finalRes.'article'.text)        
        
        $article = @{
            SqlInstance = 'sql1'
            Database    = 'AdventureWorksLT2022'
            Publication = $finalRes.'database'.text
            Schema      = $finalRes.'schema'.text
            Name        = $finalRes.'article'.text
        }
        Add-DbaReplArticle @article
